apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /tmp/tmp7411560g_run_anhhoangsky_pocker-thirteen-microservice_issue_2_3b889327/components/secrets.json